const USER_ROLES = ['ADMIN', 'SUB_ADMIN', 'AGENT'];
const TICKET_STATUSES = ['NEW', 'OPEN', 'PENDING', 'RESOLVED', 'CLOSED'];
const TICKET_PRIORITIES = ['LOW', 'MEDIUM', 'HIGH', 'URGENT'];

module.exports = {
  USER_ROLES,
  TICKET_STATUSES,
  TICKET_PRIORITIES
};
