const USER_ROLES = ['ADMIN', 'SUB_ADMIN', 'AGENT'];
const TICKET_STATUSES = ['NEW', 'OPEN', 'PENDING', 'RESOLVED', 'CLOSED'];
const TICKET_PRIORITIES = ['LOW', 'MEDIUM', 'HIGH', 'URGENT'];
const MESSAGE_AUTHOR_TYPES = ['REQUESTER', 'AGENT'];
const TICKET_EVENT_TYPES = [
  'CREATED',
  'ASSIGNED',
  'STATUS_CHANGED',
  'PRIORITY_CHANGED',
  'MESSAGE_ADDED'
];

module.exports = {
  USER_ROLES,
  TICKET_STATUSES,
  TICKET_PRIORITIES,
  MESSAGE_AUTHOR_TYPES,
  TICKET_EVENT_TYPES
};
